### ISSUE TITLE
Two factor authentication

### ISSUE THREAD

**Issue by t2d** [systemli/userli#115]
Implement an easy 2FA solution with a symfony package. Maybe just OTP or U2F. It's only focused on the web interface, not IMAP/POP3.

**Comment by doobry-systemli** [comment]
I started looking into this. The rough plan is:

* Second factor is only required for userli login (not IMAP/POP3/SMTP).
* For now only TOTP/google authentcator support. Webauthn etc. can come later.
* Second factor can be set, recreated and deleted in account settings. User password is required for all of them.
* Second factor gets deleted during recovery process.
* Support for backup codes.

Would be nice to hear about comments and thoughts on this :blush:

**Comment by t2d** [comment]
Generally, any work on this is highly appreciated. Thanks!
Can you clarify the rationale behind just enabling it for HTTPS? In my opinion, this doesn't make too much sense without the ability to enable device-spcific passwords for IMAP etc.

**Comment by t2d** [comment]
Also, have you looked at https://github.com/web-auth/webauthn-symfony-bundle?
I'm not sure, but maybe webauthn isn't much more effort than TOTP?

**Comment by doobry-systemli** [comment]
By the way, I plan to use https://symfony.com/bundles/SchebTwoFactorBundle/ for the Two-factor implementation.

**Comment by t2d** [comment]
I agree, thanks for explaining the reasoning.
