### ISSUE TITLE
boolean variables in dotenv

### ISSUE THREAD

**Issue by doobry-systemli** [systemli/userli#122]
Apparently, boolean dotenv variables only work as expected with `0`/`1` as value. We have `HAS_SINA_BOX="false"`, which results in `$hasSinaBox=true` since it is a string which is expanded to `true` when the variable gets converted to a boolean in PHP.

We should replace `HAS_SINA_BOX="false"` by `HAS_SINA_BOX=0` in `.env.dist`, `.env.test` and `README.md`.

**Comment by t2d** [comment]
there is some other problems with our dotenv setup at the moment. We should address them together
f.e. https://github.com/systemli/user-management/commit/33667eb2292d4fd73359ab20836317bdb2bb654c#commitcomment-31151179
