### ISSUE TITLE
Better way to invoke checkpassword script

### ISSUE THREAD

**Issue by doobry-systemli** [systemli/userli#127]
Right now, the checkpassword script might be invoked by system users other than the web application. On our systems, that's namely the dovecot user. This brings several problems:

* The application directory needs to be readable by all those users
* The cache directory `var/cache` needs to be writeable by all those users, as checkpassword invokation might create new cache files. This also leads to files in `var/cache` being owned by those users.
* Config files with sensitive data like `.env` or `config/parameters_prod.yaml` need to be readable by all those users

We should think about how to improve this situation. One option would be to always run checkpassword as web application user via sudo. I think, we should do this (and emphasize it in the docs).

**Comment by t2d** [comment]
Yes, that would be great. I didn't manage it, when I tried with the php checkpassword script. But maybe you can manage with the bash variant now.

**Comment by doobry-systemli** [comment]
I spend quite some hours today trying to get checkpassword running via sudo. The result is frustrating: seems like it's not possible. You have to allow several flags in sudo (enable `closefrom_overrid` and disable `env_reset`) and then still it doesn't work for some reason.

Best solution I could find is make the `checkpassword` shell script invoke all the `bin/console app:user:*` commands via sudo. That works very reliable and theoretically it would be enough for us. 

My suggestion is to add a `-u <user>` commandline option to the checkpassword script: if it's set, then the `bin/console` commands are run via sudo as user `<user>`, if it's unset, no sudo.

What do you think? Would this be ok for you?

**Comment by t2d** [comment]
would be totally okay. thanks for your work. checkpassword is horrible. Do you want to schedule this for [2.1.0](https://github.com/systemli/userli/milestone/10) since it concerns deployment?

**Comment by doobry-systemli** [comment]
Yeah, thanks for the suggestion. I added it to milestone 2.1.0.
