### ISSUE TITLE
Copy button for invitation links is broken

### ISSUE THREAD

**Issue by 0x46616c6b** [systemli/userli#165]
**Steps to reproduce**

- Log in and go to `/voucher`
- Click on gray button inside the voucher item
- Clipboard contains `undefined`

**Expected**

After clicking on the button I expect to get the invite url.

**Comment by t2d** [comment]
Can't reproduce. It works for me.

**Comment by 0x46616c6b** [comment]
With deactivated uBlock Origin (Firefox 66.0.2) it works also for me.

**Comment by t2d** [comment]
For me it works with Firefox and ublock origin. Maybe a specific rule set? Can this be closed?

**Comment by doobry-systemli** [comment]
For me this definitely was broken as well a few days ago (with ublock origin). Now it's working again (with ublock origin). No idea what changed.

@0x46616c6b: is it still broken for you?

**Comment by t2d** [comment]
Haha, I was able to find the bug. The link is undefined if you click on the glyphicon, but it works if you click on the button surrounding it. 

```
el.value = element.target.dataset.link;
```
Doesn't seem to get the right target if clicking directly on the icon.
