### ISSUE TITLE
ROLE_SPAM doesn't work as expected

### ISSUE THREAD

**Issue by doobry-systemli** [systemli/userli#177]
`ROLE_SPAM` is supposed to disable mail sending for the user in question. Seems like this doesn't work. I can still send outgoing mail with a `ROLE_SPAM` account.

**Comment by doobry-systemli** [comment]
Related: https://github.com/systemli/userli/issues/77#issuecomment-447817148

**Comment by t2d** [comment]
This seems to be a regression in the 2.2.3 release. This functionality was realized by calling 

```
USER_COMMAND="${SUDO} php $(dirname ${SCRIPT})/console app:users:check --"
```
in the `bin/checkpassword`. But there is no more functionality like this in `src/Command/CheckPasswordCommand.php`
