### ISSUE TITLE
Demo system

### ISSUE THREAD

**Issue by alexanderadam** [systemli/userli#185]
It would be nice if there would be a sandboxed demo system for getting a feeling how userli works and looks.

PS: thank you for your work!

**Comment by 0x46616c6b** [comment]
That is a nice idea. Meanwhile you can checkout the source code and starting the Vagrant Box. This will give you a complete environment accessible under http://192.168.33.99 and you can play around.

**Comment by alexanderadam** [comment]
Hi @0x46616c6b, thank you for responding so fast! I hope you had a good trip back home‽

Speaking of Vagrant:
It would be nice to have a Dockerfile and [an official image on Docker hub](https://hub.docker.com/search?q=userli&type=image) as well and or even integration into fully fledged mail setups (like [mailcow](https://github.com/mailcow/mailcow-dockerized), [Mailu](https://github.com/Mailu/Mailu), [hardware's setup](https://github.com/hardware/mailserver) or [tomav's setup](https://github.com/tomav/docker-mailserver)). :wink:

But this would be another issue.

**Comment by doobry-systemli** [comment]
Sorry for the long delay. I don't expect us to provide a live demo anytime soon. A Dockerfile is a nice idea though, but that's already tracked in #186.

**Comment by alexanderadam** [comment]
@doobry-systemli but this issue should stay open even if you can't provide a demo system soonish, right? Because it's not closed but could. And this way also other contributors could see and solve this issue if it's open.
