### ISSUE TITLE
official userli Docker container image

### ISSUE THREAD

**Issue by alexanderadam** [systemli/userli#186]
It would be nice to have a Dockerfile and [an official image on Docker hub](https://hub.docker.com/search?q=userli&type=image) as well and or even integration into fully fledged mail server setups (like [mail](https://github.com/mailcow/mailcow-dockerized/issues/410)[cow](https://github.com/mailcow/mailcow-dockerized/issues/2129), [Mailu](https://github.com/Mailu/Mailu/issues/1040), [jeboehm's setup](https://github.com/jeboehm/docker-mailserver), [tomav's setup](https://github.com/tomav/docker-mailserver/issues/1171)) or [hardware's setup](https://github.com/hardware/mailserver/issues/129).

**Comment by doobry-systemli** [comment]
Dear @alexanderadam, we're open to pull requests :blush:

**Comment by alexanderadam** [comment]
@doobry-systemli I see. I went for another solution in the meantime.
Should I close this issue then or should I keep this open so that others might profit and track this issue?

**Comment by doobry-systemli** [comment]
Thanks for the feedback! I'll close the issue for now. We can open one anytime again. At the moment it would be hard to dockerize userli anyway as Dovecot needs direct shell access to the userli commands.
