### ISSUE TITLE
    fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'php7.3-apcu' is available"}

### ISSUE THREAD

**Issue by K0XI** [systemli/userli#193]
Hi,
I got a new failure in the last step of the installation.
TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'php7.3-apcu' is available"}
This was my failure. I tryed to install php7.3-apcu but it wasn't in the apt reposetory. Because I am using Linux Debian on my server I can't using brew to install it.
Yours Sincely,
Koxi

**Comment by t2d** [comment]
Which Debian release do you use?

**Comment by t2d** [comment]
Do you have no possibility to use Debian stable? I recently dropped support for oldstable, since managing the dependencies was very different for each release.

**Comment by K0XI** [comment]
I can use Oldstable, but everytime  I use this I am not able to install all dependencys for python molecule.
E: Unable to locate package python-pyside.qtopengl
E: Couldn't find any package by glob 'python-pyside.qtopengl'
E: Couldn't find any package by regex 'python-pyside.qtopengl'

So I can't install psutil:
  Failed building wheel for psutil
and I can't install molecule:
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-x7kKes/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-lEKNzW/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-x7kKes/psutil/

**Comment by t2d** [comment]
You misunderstood me. Can you use Debian stable aka buster aka 10?

**Comment by K0XI** [comment]
No the lasdt commend is made using the Stable Version (Debian 10)

**Comment by t2d** [comment]
Sorry, for not following up earlier with you. Can you please describe, what commands lead you to this error?

**Comment by t2d** [comment]
I just tested it again. I had to re-run `sudo pip install molecule` to complete the installation of molecule. Otherwise it was working as explained [in the docs](https://systemli.github.io/userli/getting-started/).

**Comment by K0XI** [comment]
Thank you. Now it's working, but what is the standard Password for the admin Interface (IP:8080)?

**Comment by t2d** [comment]
Sorry, there is no standard password yet. I have definitely missed that. You can create some test accounts with the following command:
```
/var/www/userli/bin/console doctrine:fixtures:load
```
Afterwards, you can log in with admin:password or user:password.

**Comment by t2d** [comment]
please update to the latest version of userli to set first domain and account
