### ISSUE TITLE
Code coverage test broken

### ISSUE THREAD

**Issue by t2d** [systemli/userli#199]
Had to disable them in #198 because scrutinizer would fail.

Should we maybe try to replace scrutinizer with [SonarCloud](https://www.sonarsource.com/)?

HowTo: https://dev.to/jeromegamez/continuous-php-code-quality-with-sonarcloud-276i
There is even a Github Action to integrate it: https://github.com/SonarSource/sonarcloud-github-action

**Comment by 0x46616c6b** [comment]
Replaced Scrutinizer with SonarCloud.

**Comment by t2d** [comment]
Awesome, thank you!

**Comment by t2d** [comment]
oops, there is no coverage tests atm - re-open

**Comment by t2d** [comment]
> Current limitations/caveats of [Automatic Analysis](https://sonarcloud.io/documentation/automatic-analysis/#current-limitationscaveats)
> ...
> Code coverage information is not supported
