### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by NathanBnm** [systemli/userli#208]
I'd like to contribute but French translation isn't available on Weblate. Could you please make it available?

**Comment by t2d** [comment]
Thank you for your offer! I added the language in Weblate. https://hosted.weblate.org/projects/userli/messages/fr/
Possibly, it's a good idea to start with the help of https://www.deepl.com/translator and just see if those translations make sense to you.
Looking forward to your translations!

**Comment by NathanBnm** [comment]
Thank you! I'm already using DeepL to help me through translation, but thanks for the advice. I'll do that soon 😉

**Comment by NathanBnm** [comment]
French translation is now done.

**Comment by t2d** [comment]
Thanks a lot. It'll be in the next release.
