### ISSUE TITLE
OpenPGP key upload: Use Monospace font for text input box

### ISSUE THREAD

**Issue by trashcan55** [systemli/userli#261]
Right now a pasted ASCII key looks kind of broken

**Comment by trashcan55** [comment]
i figured i should be able to submit a PR myself once i get an understanding how templating works :sweat_smile:  
is templates/Start/openpgp.html.twig the right place to start?

**Comment by t2d** [comment]
Awesome! It is indeed https://github.com/systemli/userli/blob/master/templates/Start/openpgp.html.twig#L38

**Comment by doobry-systemli** [comment]
That would be awesome indeed! You already found the correct template. The form (and it's elements) is defined here: https://github.com/systemli/userli/blob/master/src/Form/OpenPgpKeyType.php#L49-L53

Probably the most straight forward solution would be to add a CSS class to the TextType field as described in the [Symfony Form TextType Field documentation](https://symfony.com/doc/current/reference/forms/types/text.html#attr) and configure the class attributes in [our CSS file](https://github.com/systemli/userli/blob/master/assets/css/app.css).

**Comment by doobry-systemli** [comment]
Ah and while you're at it: I had planned to increase the Textarea size a bit to display more of the pasted ciphertext. But don't feel obligated :wink:

**Comment by trashcan55** [comment]
thanks a lot! 
Got my vagrant setup running after a while (🤯) and looking into it
