### ISSUE TITLE
random alias: mismatch between webinterface, database and notification sent via mail

### ISSUE THREAD

**Issue by nevart** [systemli/userli#307]
Version: 2.7.14

How to reproduce:

* Webinterface: Create a random alias
* Webinterface: Reloads, displays new alias with address `a@`
* Database: Lists new alias, although with address `b@` (that's the correct one)
* Notification mail: Contains `b@`
* Webinterface: After another reload, the address `b@` is listed correctly

Hope this eases debugging and finding the cause!

**Comment by t2d** [comment]
Thank you for reporting. I can replicate this problem in my dev environment. Seems to have broken with some dependency update.

**Comment by nevart** [comment]
@t2d Thank you, works as expected now.

**Comment by nevart** [comment]
@t2d Nope, sorry, I was mistaken: the interaction between the webinterface and the database looks good now.

However, the mail `New alias address created` now contains a mail with addr `c@`. IIRC, this part worked before.
