### ISSUE TITLE
`Notice: Array to string conversion` in app:users:checkpassword since last release

### ISSUE THREAD

**Issue by doobry-systemli** [systemli/userli#341]
Since the latest userli release (2.7.17), every successful authentication via `app:users:checkpassword` prints an error:

```
In Process.php line 344:

  Notice: Array to string conversion
```

This error can easily be reproduced locally by running:

```
$ echo -ne 'admin@example.org\x0password' | bin/console app:users:checkpassword /bin/true; echo $?
```

The problem was hard to spot as release 2.7.17 seems to not be pushed to `origin/main` yet, right @t2d?

It only happens after symfony/process is upgraded to version 4.4.35 or later. Downgrading to 4.4.34 fixes the issue. The relevant change in symfony/process is this one: https://github.com/symfony/symfony/commit/11ccbcd24c2e2d3f4e5897f159d1c1d23fc62a67#diff-edd51b05bf438c7cdca442e25d68f41dd0a51952a69fa0c5fa912dc31d833ef4L1188-L1192

Manually adding back the `array_filter` loop fixes the problem.

Others already reported a similar bug in https://github.com/symfony/symfony/issues/44197, but the fixes (https://github.com/symfony/symfony/pull/44208 and https://github.com/symfony/symfony/pull/44538) seem to be incomplete.

**Comment by doobry-systemli** [comment]
I reported https://github.com/symfony/symfony/issues/44940 upstream

**Comment by mejo-** [comment]
For the time being, I manually patched our instance to stop the logs from being flooded:

```patch
--- ./vendor/symfony/process/Process.php.bck	2022-01-07 00:33:12.895466225 +0100
+++ ./vendor/symfony/process/Process.php	2022-01-07 00:35:10.174820877 +0100
@@ -1175,6 +1175,11 @@
      */
     public function setEnv(array $env)
     {
+	// Process can not handle env values that are arrays
+	$env = array_filter($env, function ($value) {
+	   return !\is_array($value);
+	});
+
         $this->env = $env;
 
         return $this;
```

**Comment by doobry-systemli** [comment]
For the time being, I manually patched our instance to stop the logs from being flooded:

```patch
--- ./vendor/symfony/process/Process.php.bck	2022-01-07 00:33:12.895466225 +0100
+++ ./vendor/symfony/process/Process.php	2022-01-07 00:35:10.174820877 +0100
@@ -1175,6 +1175,11 @@
      */
     public function setEnv(array $env)
     {
+	// Process can not handle env values that are arrays
+	$env = array_filter($env, function ($value) {
+	   return !\is_array($value);
+	});
+
         $this->env = $env;
 
         return $this;
```

**Comment by doobry-systemli** [comment]
So the problem is on our side and the `symfony/process` update just revealed a bug. The way we merge the environment variables in https://github.com/systemli/userli/blob/main/src/Command/CheckPasswordCommand.php#L230 is wrong.
