### ISSUE TITLE
Dovecot starts multiple php processes which results in OOM killer

### ISSUE THREAD

**Issue by kidhab** [systemli/userli#385]
We run a low traffic mail server with around 100 mailboxes. We repeatedly (about once a week) experience the following situation:
The IMAP login process/ checkpassword starts a lot of php processes (about 100) which results in a very high system load. After the kernel kills the php process due to an out of memory situation the Dovecot process isn't available any more.

According to the monitoring the overall memory use is never a problem. We tried to limit php's `memory_limit` to a very low value like `16 M` but this didn't prevent the situation. As a workaround systemd is now restarting Dovecot in this situations (`Restart=on-failure`).

I don't expect our setup to be special in any way - so I'm curious if you encounter similiar behaviour.

**Comment by t2d** [comment]
Hey, thanks for creating this issue. What OS are you using? We've never experienced an issue like this on Debian stable.

**Comment by kidhab** [comment]
Same here: Userli is running on Debian Bullseye. Do you use any special PHP or Dovecot settings that may incluence behaviour like this?

**Comment by t2d** [comment]
Are you using https://github.com/systemli/ansible-role-userli/ ?

**Comment by t2d** [comment]
But you can find all the config there. No idea why this problem occurs for you. Sorry

**Comment by doobry-systemli** [comment]
@kidhab do you still experience this problem?

**Comment by kidhab** [comment]
Looking at our monitoring there were no anomalies for some weeks now and we didn't change anything.
