### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by pepper3k** [systemli/userli#567]
I am trying to install this software, but the documentation is VERY lacking.

If one of the devs can contact me and help me set it up, I would be happy to create some install guides for different distros or different backends (postgres, nginx etc...)

I just don't have the time to reverse engineer/debug undocumented software, while experimenting with new tools.

I have a lot of linux experience and would be happy to help out, just need to be pointed in the right direction.

**Comment by t2d** [comment]
Hi @pepper3k. Appreciate you checking out the project. Did you have a look at our ansible role https://github.com/systemli/ansible-role-userli? Even if you don't use ansible, it's basically a step-by-step guide to setup the system on Debian.

I agree that the manual installation guide is in a sorry state, but I don't think we're in a position to give individualized support.

**Comment by pepper3k** [comment]
@t2d I did, failed miserably lol, i will try again next week though
