### ISSUE TITLE
Click on deleted alias in AliasAdmin produces NotFoundHttpException 

### ISSUE THREAD

**Issue by t2d** [systemli/userli#61]
# How to reproduce

1. Delete existing alias (f.e. 4)
2. Go to admin/alias/list (alias 4 is still listed)
3. Go to admin/alias/4/edit/

**Comment by 0x46616c6b** [comment]
I can't reproduce this anymore. Can you?

**Comment by t2d** [comment]
I now get this page
![image](https://github.com/systemli/userli/assets/1834580/80282f9b-4976-4e22-a558-e50760c5296b)

**Comment by t2d** [comment]
thank you. it's fixed now
