### ISSUE TITLE
Please allow users to remove custom alias'

### ISSUE THREAD

**Issue by nevart** [systemli/userli#627]
They're able to create these, so please allow them to get rid of them as well.

**Comment by doobry-systemli** [comment]
I have good news, this already exists:

```
./bin/console app:alias:delete --user user@example.org --alias alias@example.org
```

This will only delete aliases if they match the given user, which is handy to use if you don't want to check manually if a user really owns the alias they asked to be deleted.

**Comment by doobry-systemli** [comment]
Ah, sorry, I misunderstood. The reason why we didn't implement this, is that this can be used for DOS attacks: users could register and delete many aliases and that way exhaust the space of nice mail addresses. We for sure can discuss if our opinion on this changed.
