### ISSUE TITLE
Add support for dovecot dict authentication (replace checkpassword)

### ISSUE THREAD

**Issue by doobry-systemli** [systemli/userli#75]
In order to get rid of the ugly checkpassword hacks, we might consider to add support for a key-value database or authentication server that works with [Dovecot's dict authentication lookups](https://wiki.dovecot.org/AuthDatabase/Dict).

**Comment by y3n4** [comment]
Closing this since we went for the Lua authentication driver https://github.com/systemli/userli/pull/651
